AWSTemplateFormatVersion: "2010-09-09"
Description: Air Corp Pipeline CFT

Parameters:
  KmsKeyName:
    Type: String
  S3BucketName:
    Type: String
  IAMRoleName:
    Type: String 
  OrgTag: 
    Type: String
  TeamTag:
    Type: String 
  AppTag:
    Type: String
  EnvTag:
    Type: String
Resources:
  S3Key:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: An example symmetric encryption KMS key
      EnableKeyRotation: true
      PendingWindowInDays: 20
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::555887476308:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::555887476308:root'
            Action:
              - 'kms:Create*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Update*'
              - 'kms:Revoke*'
              - 'kms:Disable*'
              - 'kms:Get*'
              - 'kms:Delete*'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
            Resource: '*'
          - Sid: Allow use of the key
            Effect: Allow
            Principal:
              AWS: !Sub "${OrgTag}-${TeamTag}-${AppTag}-${IAMRoleName}-${EnvTag}"
            Action:
              - 'kms:DescribeKey'
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey'
            Resource: '*'
      Tags:
      - Key: Organization
        Value: !Ref OrgTag
      - Key: Team
        Value: !Ref TeamTag
      - Key: Application
        Value: !Ref AppTag
      - Key: Enviornment
        Value: !Ref EnvTag

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName 
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: !Ref S3Key
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Organization
          Value: !Ref OrgTag
        - Key: Team
          Value: !Ref TeamTag
        - Key: Application
          Value: !Ref AppTag
        - Key: Enviornment
          Value: !Ref EnvTag

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BucketName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "${OrgTag}-${TeamTag}-${AppTag}-${IAMRoleName}-${EnvTag}"
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:ListBucket'
            Resource: 
              - !GetAtt S3Bucket.Arn
              - !Sub '${S3Bucket.Arn}/*'
Outputs:
  S3BucketArn:
    Value: !GetAtt S3Bucket.Arn
  KMSKeyArn:
    Value: !GetAtt S3Key.Arn