AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Policy

Parameters:
  OrgTag: 
    Type: String
  TeamTag:
    Type: String 
  AppTag:
    Type: String
  EnvTag:
    Type: String
  IAMRoleName:
    Type: String
  KMSKeyArn:
    Type: String 
  S3BucketArn:
    Type: String
  PolicyName:
    Type: String 
Resources:
  IAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles: 
        - !Sub "${OrgTag}-${TeamTag}-${AppTag}-${IAMRoleName}-${EnvTag}"
      PolicyName: !Sub "${OrgTag}-${TeamTag}-${AppTag}-${PolicyName}-${EnvTag}"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: UsageofExternalKMSKey
            Effect: Allow
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource: !Sub '${KMSKeyArn}'
          - Sid: UsageofExternals3Bucket
            Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:ListBucket'
            Resource: 
              - !Ref S3BucketArn
              - !Sub '${S3BucketArn}/*'
