AWSTemplateFormatVersion: "2010-09-09"
Description: Air Corp Pipeline CFT

Parameters:
  IAMRoleName: 
    Type: String
    Default: Corp5-Mythos-Practice-Chris-IAM-Role
Resources:
  IAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref IAMRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
Outputs:
  KmsKeyArn:
    Value: !GetAtt IAMRole.Arn
